name = "apass"
description = "A CLI password generator written in Ada."
version = "0.0.1"

authors = ["Simon Rowe"]
maintainers = ["Simon Rowe <simon@wiremoons.com>"]
maintainers-logins = ["wiremoons"]

executables = ["apass"]

