name = "apass"
description = "A CLI password generator written in Ada."
version = "0.0.5"

authors = ["Simon Rowe"]
maintainers = ["Simon Rowe <simon@wiremoons.com>"]
maintainers-logins = ["wiremoons"]

executables = ["apass"]


[[depends-on]]  # This line was added by `alr with`
gnatcoll = "^21.0.0"  # This line was added by `alr with`
